#!/bin/bash
#SBATCH --job-name=M2_mixer    # nom du job
#SBATCH --partition=cpu          # choix de la priorité (ici cpu) 
#SBATCH --nodes=1                # nombre de noeuds
#SBATCH --ntasks=1               # nombre total de tâches sur tous les nœuds
#SBATCH --cpus-per-task=8        # nombre de coeur cpu par tâche (>1 si tâches multi-threaded)
#SBATCH --mem=64G         
#SBATCH --time=8:00:00          # le temps total de run (HH:MM:SS)
#SBATCH --output=/home/yanis.gerst/slurm/output_file         # nom du fichier de sortie
#SBATCH --error=/home/yanis.gerst/slurm/error_file          # nom du fichier erreur
#SBATCH --mail-user=yanis.gerst@etu.univ-amu.fr
#SBATCH --mail-type=all     


echo "Executing on the machine:" $(hostname)

module purge
# Load Modules 
srun python audio_to_spec.py 
